# react import setup
jsx = "react"
jsxFragment = "Fragment"
jsxImportSource = "react"

[test]
# test coverage thresholds
coverageThreshold = { lines = 0.97, functions = 1 }
# load happydom package to ensure @testing-library/react compatibility
preload = "./.happydom.ts"
