const config = {
  entryPoints: [
    "src/utils",
    "src/sizes",
    "src/types",
    "src/typography",
    "src/components",
    "src/layouts",
  ],
  exclude: [
    "**/*.component.tsx",
    "**/*.test.tsx",
    "**/*.test.ts",
    "**/*.stories.tsx",
    "**/*.stories.ts",
  ],
  name: "@ubloimmo/uikit",
  includeVersion: true,
  includeHierarchySummary: true,
  readme: "./README.md",
  out: "./docs/pages/typedoc",
  plugin: ["typedoc-plugin-markdown", "./scripts/docs/typedoc.plugin.js"],
  theme: "mdx-theme",
  outputFileStrategy: "members",
  membersWithOwnFile: [
    "TypeAlias",
    "Interface",
    "Enum",
    "Function",
    "Class",
    "Variable",
  ],
  fileExtension: ".mdx",
  logLevel: "Verbose",
  hideBreadcrumbs: true,
  useCodeBlocks: false,
  mergeReadme: true,
  expandObjects: true,
  expandParameters: true,
  hidePageTitle: true,
  typeDeclarationVisibility: "verbose",
};

export default config;
