/**
 * Creates an array of specified length where each element is generated by the provided creator function.
 * Used in stories to generate array of sample components
 *
 * @param {number} length - The length of the array to be created.
 * @param {(index: number) => TItem} creatorFn - The function that generates the elements of the array.
 * @return {TItem[]} The array with elements generated by the creator function.
 */

export const arrayOf = <TItem>(
  length: number,
  creatorFn: (index: number) => TItem
) => Array.from({ length }, (_, index) => creatorFn(index));
