# GitHub action that
# - Increment package version revision (0.1.2 => major.minor.revision)
# - Builds an NPM package
# - Publishes it to NPM
# - Commits the build to the "build" branch
# - Call release workflow
# Runs
# - on each commit to main with a new version
# - manually in the "actions" tab of the repository

name: Publish
run-name: Publishing
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "Release type (one of): patch, minor, major, prepatch, preminor, premajor, prerelease"
        required: true
        type: string

jobs:
  prepare_publish:
    name: Prepare Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup node
        id: node_setup
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Check node
        id: node_check
        run: |
          which node
          node --version
          which npm
          npm --version

      # Configure Git
      - name: Setup git
        id: git_setup
        env:
          CI_COMMIT_AUTHOR: CI
          CI_COMMIT_EMAIL: ci@users.noreply.github.com
        run: |
          git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"

      # Bump package version
      # Use tag latest
      - name: Bump release version
        if: startsWith(github.event.inputs.release-type, 'pre') != true
        run: |
          echo "NEW_VERSION=$(npm --no-git-tag-version version $RELEASE_TYPE)" >> $GITHUB_ENV
          echo "RELEASE_TAG=latest" >> $GITHUB_ENV
          echo "NEW_VERSION="$NEW_VERSION" >> $GITHUB_OUTPUT

        env:
          RELEASE_TYPE: ${{ github.event.inputs.release-type }}

      # Bump package pre-release version
      # Use tag beta for pre-release versions
      - name: Bump pre-release version
        if: startsWith(github.event.inputs.release-type, 'pre')
        run: |
          echo "NEW_VERSION=$(npm --no-git-tag-version --preid=beta version $RELEASE_TYPE)" >> $GITHUB_ENV
          echo "RELEASE_TAG=beta" >> $GITHUB_ENV
        env:
          RELEASE_TYPE: ${{ github.event.inputs.release-type }}

      # Update changelog unreleased section with new version
      - name: Update changelog
        uses: superfaceai/release-changelog-action@v1
        with:
          path-to-changelog: CHANGELOG.md
          version: ${{ env.NEW_VERSION }}
          operation: release

      # Commit changes
      - name: Commit CHANGELOG.md & package.json changes and create tag
        run: |
          git add "package.json"
          git add "CHANGELOG.md"
          git commit -m "chore: release ${{ env.NEW_VERSION }}"
          git tag ${{ env.NEW_VERSION }}

      # Push repository changes
      - name: Push changes to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main && git push --tags

  trigger_publish:
    name: "Trigger lib publish"
    needs: prepare_publish
    uses: "./.github/workflows/lib_publish.yml"
    secrets: inherit
    with:
      pre-release: ${{ startsWith(github.event.inputs.release-type, 'pre') }}
