# GitHub action that
# - Creates a new release
# When
# - a new package version is published
# - ran manually

name: Release
run-name: Creating release
on:
  workflow_call:
    inputs:
      pre-release:
        description: "Whether the new release is a pre-release"
        required: false
        type: boolean

jobs:
  create_release:
    name: "Create release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup jq
        id: jq_setup
        uses: dcarbone/install-jq-action@v2.1.0

      - name: Check jq
        id: jq_check
        run: |
          which jq
          jq --version

      - name: Setup zip
        id: zip_setup
        uses: montudor/action-zip@v1.0.0

      - name: Check zip
        id: zip_check
        run: |
          which zip
          zip --version

      - name: Get release version
        id: release_version
        run: |
          version=$(echo $(<./package.json) | jq ".version")
          echo "version=$version" >> $GITHUB_OUTPUT

      # Read version changelog
      - name: Get version changelog
        id: changelog_get
        uses: superfaceai/release-changelog-action@v1
        with:
          path-to-changelog: CHANGELOG.md
          version: ${{ steps.release_version.outputs.version }}
          operation: read

      - name: Create release
        id: release_create
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release_version.outputs.version }}
          name: "Release v${{ steps.release_version.outputs.version }}"
          body: ${{ steps.changelog_get.outputs.changelog }}
          draft: false
          prerelease: ${{ github.event.inputs.pre-release }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
